import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { client } from './_app'
import { ALL_CHARACTERS } from '../graphql/queries'
import Link from 'next/link'
import Cards from '../components/Cards'

export default function Home ({ data, page, count }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          {data.map(p => <Cards key={p.id} data={p} />)}
        </div>
        <div className={styles.buttons}>
          {page > 1 && <Link href={{ pathname: '/', query: { page: 1 } }}>init</Link>}
          {page > 1 && <Link href={{ pathname: '/', query: { page: page - 1 } }}>prev</Link>}
          {page < count && <Link href={{ pathname: '/', query: { page: page + 1 } }}>next</Link>}
          {page < count && <Link href={{ pathname: '/', query: { page: count } }}>last</Link>}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps (context) {
  const page = parseInt(context.query.page) || 1
  const { data, loading } = await client.query({
    query: ALL_CHARACTERS,
    variables: {
      page
    }
  })

  return {
    props: {
      data: data.characters.results,
      page,
      count: 42
    }
  }
}
